name: pypi

on: 
  push:
    branches: [42-enhancement-make-python-package-available-for-pip-and-uv-no-local-build-needed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CONAN_HOME: "${{ github.workspace }}/conan2"
    strategy:
      matrix:
        os: [macos-26]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

#      - name: Install build environment and setup tooling
#        run: |
#          sudo apt-get update
#          sudo apt-get install --no-install-recommends -y build-essential cmake python-is-python3 python3-pip python3-dev lsb-release

#      - name: Set up Python and build tools
#        uses: actions/setup-python@v6
#        with:
#          python-version: "3.13"

#      - name: Install Python dependencies
#        run: pip install uv 'conan>=2.28' numpy twine

#      - name: Retrieve version
#        id: retrieve-version
#        run: |
#          DIST_ID=$(lsb_release -i -s 2>/dev/null)
#          DIST_MAJOR=$(lsb_release -r -s | cut -d. -f1 2>/dev/null)
#          DISTRIBUTION=${DIST_ID}${DIST_MAJOR}
#          echo "Determined OS: ${DISTRIBUTION}"
#          echo "DISTRIBUTION=${DISTRIBUTION}" >> "$GITHUB_OUTPUT"
#
#          PYTHON_VERSION=$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}");')
#          echo "Determined Python: ${PYTHON_VERSION}"
#          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITHUB_OUTPUT"

#      - name: Cache/Restore dependencies
#        uses: actions/cache@v5
#        with:
#          path: ${{ env.CONAN_HOME }}
#          key: ${{ runner.arch }}-${{ steps.retrieve-version.outputs.DISTRIBUTION }}-python${{ steps.retrieve-version.outputs.PYTHON_VERSION }}-${{ hashFiles('**/conanfile.py') }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1

#      - name: Clean conan cache
#        run: |
#          conan cache clean

#      - name: Unit-Test package
#        run: |
#          pip install dist/ticket_decoder*.whl
#          python -m unittest discover -s source/test/python/

#      - name: Verify package
#        run: twine check dist/*

#      - uses: actions/upload-artifact@v7
#        with:
#          name: ${{ runner.arch }}-${{ steps.retrieve-version.outputs.DISTRIBUTION }}-python${{ steps.retrieve-version.outputs.PYTHON_VERSION }}
#          path: dist/

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    environment: staging
    needs: build
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
