name: pypi

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Publish to test.pypi.org'
        required: true
        default: 'staging'

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    env:
      CONAN_HOME: "${{ github.workspace }}/conan2"
    strategy:
      matrix:
        os: [
          macos-26,
          # macos-15-intel,
          ubuntu-24.04,
          ubuntu-24.04-arm
        ]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  publish-test:
    name: Publish to test.pypi.org
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://test.pypi.org/project/ticket-decoder
    needs: [build, sdist]
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist/
          merge-multiple: true

      - name: Publish package distributions to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
