name: x86_64-macos14-clang15

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '23 3 2,12,22 * *'

env:
  CLANG_VERSION: 16
  CONAN_USER_HOME: ${{ github.workspace }}/conan

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build environment
        run: |
          python3 -m venv .venv && . .venv/bin/activate && pip install "conan" "numpy<2.0"

      - name: Setup conan
        run: . .venv/bin/activate && etc/conan-config.sh apple-clang $CLANG_VERSION


      - name: Cache/Restore dependencies
        uses: actions/cache@v4
        with:
          path: ./conan
          key: ${{ runner.os }}-${{ github.workflow }}-conanfile-${{ hashFiles('conanfile.py') }}

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          etc/poppler/setup.sh
          etc/conan-install.sh Release

      - name: Build
        run: |
          etc/cmake-config.sh Release
          etc/cmake-build.sh Release -- -j

      - name: Unit-Test C++
        run: |
          etc/install-uic-keys.sh
          build/Release/bin/ticket-decoder-test

      - name: Unit-Test Python3
        run: etc/python-test.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ticket-decoder
          path: |
            build/Release/etc/*
            build/Release/lib/*
            build/Release/bin/*
